### PR TITLE
Update RAQUASI88

### PR DESCRIPTION
**Pull request by rzumer**
* Only process achievements while executing
* Fix an issue where loading a disk image in drive 2 would clear the loaded title

Should be tagged as 1.1.1 for a hotfix update.

### CODE REVIEW

**Comment by rzumer** [comment]
Also, please do not squash, as the subtree needs to keep track of the last commit merged. Squashing PRs causes the subtree pull to start over from the beginning and causes merge conflicts every time.

**Comment by Jamiras** [comment]
To avoid issues with "squashing", I recommend creating new branches for new features/bugfixes instead of reusing the same one over and over again. The squash creates a single commit for a single change in master and keeps the master tree cleaner. If individual commits must be referenced, the linked PR still maintains those.

**Comment by rzumer** [comment]
I am not sure what you mean; I reuse the same branch for my updates, but it is always rebased onto the current master prior to each PR, so it is practically the same as submitting a PR from a separate branch every time. I am also squashing my changes as you can see from the history, but the subtree command needs to generate a merge request regardless, and I think it is these merge commits that it uses to keep track of the subtree tip.

**Comment by Jamiras** [comment]
Using differently named branches helps to group commits together, similar to binding them with a squash commit. If you just look at the history of the "quasi88" branch, it's harder to tell where each PR starts and ends.

Squashing commits eliminates intermediate states that result from iterative development, and it's easiest to do that when merging the feature branch into another branch (typically master or develop) indicating that the feature is complete.

I'll do my best to not squash your branch if you do your best to not force-push. force-pushing rewrites history and causes "detached head" errors instead of merge conflicts.

**Comment by rzumer** [comment]
Sorry, but again, I'm not sure what you are talking about. Like I said in my last comment, my PRs reuse a branch (in my fork), and I reset its state to the master branch's after every merge. So what are you looking for in history? Are you mistaking the `quasi88` branch in this repository for my fork's, which is more up to date?

A squashed subtree pull maintains the history in the commit description and since the merge commit is seemingly required to track the subtree, it is the best way to keep the history clean on this end. As mentioned before, rebase and merge is best for the PR if you want to keep history clean, because it does not require an extra merge commit for the branch.

**Comment by rzumer** [comment]
As for the full commit history for `RAQUASI88` being written into the subtree squash-pull commit description, that is due to being forced to start over from the start of the history because, as mentioned earlier, subtree merge commits being squashed in previous PRs was interfering with subtree tracking.

**Pull request merged**
