### PR TITLE
WIP Adding Atari800 emulator to work with

### PR DESCRIPTION
**Pull request by salvadorc17**
Added emulator code to work with, it includes RaIntegration submodule and works compiles without issues.

Build results here:
https://ci.appveyor.com/project/SalvadorCabs/raemus

### CODE REVIEW

**Comment by meleu** [comment]
Have you checked the checklist?
https://github.com/RetroAchievements/RAEmus/blob/master/NewEmuChecklist.txt

**Comment by salvadorc17** [comment]
Is wip checklist, but mostly works for now

**Comment by Jamiras** [comment]
It looks like you updated the original `Atari800WinPLus.sln` release configuration, but didn't do anything for the debug configuration (it fails to compile with 48 errors - mostly unresolved RetroAchievements functions). At a minimum, you need to make sure the debug build works too, but I would recommend making new configurations for the RetroAchievements-specific builds. Instructions on how to do that is in the wiki linked below. 

Additionally, even though the release configuration does build, it doesn't run. Something seems to be moving the executable from the Release output folder to the Distribution folder, and the debugger can no longer find it. Trying to run the executable manually generates an error : `The code execution cannot proceed because libpng12.dll was not found`. This dll does not appear anywhere in the RAAtari800Win subdirectory. It does exist in the bizhawk directory, but I wouldn't expect it to be looking there. After copying that file, it complains about `zlib1.dll`, which I was also able to copy from bizhawk. This allows the executable to finally run, and it seems to be an installer.

image

At this point, I gave up. If you want me to look at this again, please create a standalone repository referencing RAInterface, and a PR that clearly indicates what changes you've made on top of the original source code. Details on how to do that are here: https://github.com/RetroAchievements/RAInterface/wiki/Creating-a-new-emulator

I expect both the debug and release configuration to compile and run by hitting F5 within the debugger. I would prefer having RA specific configurations so the non-RA build can still be generated in case we need a side-by-side functional comparison.

Having a separate repository that's in line with the upstream makes it easier to pick up upstream changes in the future. Having a "starter" PR that identifies exactly what was changed from the original repository makes it much easier to review. 

Also, you should be using the RAInterface submodule, not the RAIntegration submodule. The RAIntegration submodule in the RAEmus repository is still from 0.76. The RAInterface submodule is also quite old, but can be updated. Updating RAIntegration will not work as it no longer contains the files that were moved to RAInterface.

**Comment by salvadorc17** [comment]
Thats setup wizard indeed , you only setup if for first time, but i will try to do Retroachievements configuration separated from original ones.

**Pull request closed without merging**
