### PR TITLE
Add RAppleWin

### PR DESCRIPTION
**Pull request by rzumer**
Please see the upstream repository (https://github.com/rzumer/AppleWin/tree/cheevos) for history.

It reuses some of the framework used in RAQUASI88 for disk swapping support and switching to writable disk image copies to avoid overwriting original disk data. Runtime disk copies should appear in a `SAVE` directory (will be created if it does not exist), though I did not test it very much. Hashing is exactly the same as with RAQUASI88, i.e. full file, for the first drive only.

Memory mapping is the full 128KB memory space, i.e. the main and auxiliary banks, each 64KB. The auxiliary bank could be cleared when booting to a system that does not support it (i.e. pre-IIe), but currently it is mapped in its uninitialized state, which should be consistent with the memory state when booting a title that does not support auxiliary RAM on a system that does.

To do:
* [x] Better error handling on file load/session restore
* [x] Fix RetroAchievements dialogs not displaying
* [x] Fix pause overlay menu immediately going out of pause
* [x] Fix NULL window handle
* [x] Investigate frequent crashes
* [x] Investigate memory mapping specifics
  * [x] Determine why main + auxiliary RAM mapping does not work for some titles
* [x] Check memory map consistency with and without auxiliary RAM (i.e. cross-machine compatibility)
* [x] Go over the checklist
* [x] Test somewhat thoroughly
* [x] Update Game Identification wiki page
* [x] Update Memory mapping wiki page
* [x] Move to the repository-local `RAIntegration` version (once support is merged in)
* [x] https://github.com/RetroAchievements/RAIntegration/issues/314

### CODE REVIEW

**Comment by rzumer** [comment]
Right now it seems to break down quite hard when anything goes wrong, and since it saves the last loaded file in registry it can get into a state where it crashes on every boot. Will try to fix tomorrow.

**Comment by rzumer** [comment]
Current checklist state:

- [ ] Game Identification
  - [x] Hash method documented
    - [ ] and approved
  - [x] If emulator supports dynamic patching [i.e. ips], hash is calculated after applying patch
  - [x] Hash ignores any persistent save data [SRAM]
  - [x] Game can be properly identified (RA_OnLoadNewRom and/or RA_IdentifyROM + RA_ActivateGame)
  - [x] Unidentified game provides some descriptor [typically filename] to unknown game dialog (RA_InstallSharedFunctions>RA_GetEstimatedGameTitle)
  - [x] Unidentified game provides list of known games for console (RA_SetConsoleID - which is usually called by RAIntegration in the emulator registration)
- [ ] Emulator
  - [x] DLL is downloaded if not available (RA_Init - new EmulatorID enum value may be needed in RA_Interface.h)
  - [x] RetroAchievements menu is visible (RA_CreatePopupMenu) and functional (RA_InvokeDialog)
  - [x] RetroAchievements menu updates when logging in/out (RA_InstallSharedFunctions>RA_RebuildMenu)
  - [x] Login dialog displayed on first run or auto-login on future runs (RA_AttemptLogin)
  - [x] Title includes logged in user (RA_UpdateAppTitle)
  - [x] RALog.txt ends with "Shutdown complete" after closing emulator (RA_Shutdown)
  - [x] Full-window overlay can be displayed (RA_SetPaused)
  - [x] Full-window overlay can be navigated (RA_UpdateRenderOverlay>pInput)
  - [ ] Full-window overlay navigation uses player's custom controller bindings, not hard-coded inputs. -> irrelevant, Apple II uses keyboard input and mapping is not layout-dependent
  [x] Closing the full-window overlay unpauses the emulator (RA_InstallSharedFunctions>RA_CauseUnpause)
  [x] Resetting the emulator disables any active popups/leaderboards (RA_OnReset)
  [ ] Performance of emulator (without any debugging windows open) should not be noticeably different than the source emulator at 100% speed -> definitely not, but I am quite sure the same can be said of all RA emulators. I doubt it is something I can control.
  [x] Emulator must perform at intended framerate on a PC that could have been purchased at a retail store within the last four years.
[ ] Achievements/Leaderboards/Rich Presence
  [x] Achievements can be created (RA_InstallSharedFunctions>RA_GameIsActive)
  [x] Achievements trigger (RA_InstallMemoryBank>pReader, RA_DoAchievementsFrame, RA_HandleHTTPResults)
  [x] Achievement trigger displays notification (RA_UpdateRenderOverlay)
  [x] Achievement can pause emulator [Pause on Reset, Pause on Trigger] (RA_InstallSharedFunctions>RA_CausePause)
  [x] Achievements are not processed when emulator is paused [HitCount for true condition does not increment] (RA_DoAchievementsFrame not called when paused)
  [x] When using frame advance, achievements are only processed when the frame is advanced.
  [x] Changing the current game prompts the user to save modifications (RA_ConfirmLoadNewRom)
    [x] Choosing not to save modifications aborts changing the current game.
  [ ] Closing the emulator prompts the user to save modifications (RA_ConfirmLoadNewRom) -> to check
    [ ] Choosing not to save modifications aborts closing the emulator.
  [x] Closing the current game prompts the user to save modifications (RA_ConfirmLoadNewRom)
    [x] Choosing not to save modifications aborts closing the current game.
  [x] Closing the current game clears the list of achievements for the game (RA_OnLoadNewRom(NULL,0))
[x] Softcore
  [x] Save states can be created
  [x] Save states can be loaded
  [x] HitCounts persist with save state (RA_OnSaveState, RA_OnLoadState)
  [x] Fast-forward is allowed
  [ ] Rewind is allowed -> N/A
  [x] Frame advance is allowed
  [ ] Recording playback is allowed -> N/A
  [x] Overlay should not be displayed when using frame advance (don't call RA_SetPaused)
  [x] Switching to Hardcore resets the emulator (RA_InstallSharedFunctions>RA_ResetEmulation)
  [x] Switching to Hardcore resets the emulator speed to 100%
  [x] Switching to Hardcore closes any emulator specific tools for viewing/modifying memory
  [ ] Switching to Hardcore disables any enabled cheats -> N/A
  [x] Modifying memory affects the game (RA_InstallMemoryBank>pWriter)
[x] Hardcore
  [x] Save states can be created
  [x] Save states cannot be loaded [prompt to switch to softcore (RA_WarnDisableHardcore)]
  [x] Fast-forward is allowed
  [x] Rewind is not allowed
  [x] Frame advance is not allowed
  [ ] Recording playback is not allowed -> N/A
  [x] Speed may be adjusted above 100% -> isn't that the same thing as fast-forward/rewind above?
  [x] Speed cannot be adjusted below 100%
  [x] Switching to Softcore does not reset the emulator
  [x] Emulator specific tools for viewing/modifying memory are not allowed [prompt to switch to softcore optional]
  [ ] Emulator specific tools for supporting cheats are not allowed [prompt to switch to softcore optional] -> N/A
  [x] Ensure any features not allowed in hardcore are disabled both from menu items and hotkeys
[ ] After approval
  [ ] Version generated from git tag
  [ ] Zip file needs to be built - should contain emulator, default Overlay directory, and any supplemental files needed by the emulator
  [ ] Backend (to be done by the RAWeb team)
    [ ] Add the emulator's console ID as a "valid" console, so new achievements can be promoted to the Core set (RAWeb:lib/database/game.php>isValidConsoleId).
    [ ] Add the emulator's enum (get the number from RAInterface.h and add it in RAWeb:src/Emulators.php)
    [ ] dorequest.php>latestclient needs to map to LatestXXXVersion.html file when it receives either emulator ID or console ID.
    [ ] Zip file needs to be uploaded to server
    [ ] Create the LatestXXXVersion.html page.
[ ] Add a link to the zip file and show the latest emulator's version in download.php

**Comment by Jamiras** [comment]
I approve the hashing method. I'd prefer something that only hashed the contents of the disk (see https://a2ciderpress.com/mdc-out.txt), but as that doesn't solve the problem of having save files on the disk, there's minimal benefit to being selective about what gets hashed - just be prepared to answer to the masses if they can't get their images to load (most of mine don't match the already registered hashes).

I agree that custom inputs are irrelevant for the overlay given that there isn't any ability to customize the input.

I couldn't figure out how to activate "frame advance" to validate the items related to "frame advance". The closest I could find is the debugger, which didn't seem to ever call `RA_DoAchievementsFrame`, no matter how long I held down the spacebar.

Also, Ctrl+ScrollLock and Ctrl+Break both pop out into some sort of [emulated debugger](http://www.easy68k.com/paulrsm/6502/MONREF.HTM). I couldn't figure out how to get back into the game, but was able to trigger achievements by modifying memory. This should be disabled for Hardcore mode.

> * Speed may be adjusted above 100% -> isn't that the same thing as fast-forward/rewind above?

Emulator speed refers to setting the overall speed of the emulator to some value above or below the normal speed. For example, in RANes, you can set the emulator speed to "50%" to only process 30 frames per second, or "200%" to process 120 frames per second. Using fast forward temporarily removes any throttling, allowing the emulator to run as fast as possible. I believe this is reflected by the "Custom Speed" slider in the configuration window, which is currently not limited by Hardcore mode.

I also noticed the following things, but don't believe them to be blockers.
* Prompt for unsaved changes occurs after Unknown ROM dialog. This may be a side-effect of supporting disk-swapping.
  * Choosing "no" cancels the load, but causes an error dialog: "unable to open file XXX.dsk". 
* Hardcore warning is shown after selecting the save state to load.
* Switching to hardcore mode with the debugger open prompts to disable hardcore mode, but does close it if selecting "no"

**Comment by rzumer** [comment]
I considered skipping some disk data, but to help with mismatched disks at all it would have to be very sophisticated as far as I can tell. Besides copies that are distributed with save files already written to them, most public dumps are cracked versions, sometimes have trainers or cheats embedded inside, and usually have added splash screens that would be part of the hashed contents anyway. There are multiple supported formats too, so decoding them to a common one would probably be more trouble than it's worth, especially if other emulators, e.g. any future libretro core, have to reproduce it.

>I believe this is reflected by the "Custom Speed" slider in the configuration window, which is currently not limited by Hardcore mode

It is restricted to softcore mode when set under 100%.

The other two blocking issues should be fixed.

**Comment by Jamiras** [comment]
> I couldn't figure out how to activate "frame advance" to validate the items related to "frame advance". The closest I could find is the debugger, which didn't seem to ever call RA_DoAchievementsFrame, no matter how long I held down the spacebar.

Confirmed that `RA_DoAchievementsFrame` is now eventually called while holding down the spacebar. This doesn't really feel like a proper frame advance as what is present in the other emulators, but does validate the required behavior: achievements are only processed when the frame advances and the behavior is not available in hardcore mode.

Verified that Ctrl+Break and Ctrl+ScrollLock no longer open the emulated debugger. This is also true for non-hardcore mode, which is probably a wise decision given that it seems to be impossible to get back to the game once activated.

Also verified the custom speed slider - was not expecting the validation to only occur on closing the dialog.

Unless you have anything else you want to do, I'm ready to merge this and tag it as 1.0.

**Comment by rzumer** [comment]
Seems good to me, thanks for validating.

**Pull request merged**
