### PR TITLE
Add RAQUASI88

### PR DESCRIPTION
**Pull request by rzumer**
This adds the RetroAchievements branch of my QUASI88 fork via `git-subtree`, so it can be later updated or moved without breaking changes one way or the other.

Left as possible future work:
- Map text VRAM (AKA high speed RAM) and main VRAM, if needed
- Support CD-ROM media
- English documentation

To-do (non-blocking):
- [ ] Compilation guide
- [ ] Basic user documentation (ROM dependencies, disk formatting & loading, etc.)
- [ ] Deployment script(s)
  - [ ] Create release subdirectories automatically (DISK, ROM, etc.)

Please let me know when this is mergeable so that I can force-push a new sub-tree and get rid of the additional merge commits.

Related: https://github.com/RetroAchievements/RAIntegration/pull/216

### CODE REVIEW

**Comment by rzumer** [comment]
Full overlay support is now implemented, so I consider this PR ready to merge.

**Comment by Jamiras** [comment]
There are several things that I feel need to be addressed before this can be merged. At a minimum, I expect to be able to build and debug the application using a fresh checkout. Here are the errors I ran into, and an itemized list of things I'd like to see changed:

---------
[ ] A fresh checkout should not generate modified files. And why can't I make them go away?
```
> git clone https://github.com/RetroAchievements/RAEmus.git
> cd RAEmus
> git checkout quasi88
> git status
On branch quasi88
Your branch is up-to-date with 'origin/quasi88'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   RAQUASI88/src/snddrv-old/src/unix/sysdep/sysdep_sound_stream.c
        modified:   RAQUASI88/src/snddrv/license.txt
        modified:   RAQUASI88/src/snddrv/mame.txt
        modified:   RAQUASI88/visualc/KEYCONF.ini
        modified:   RAQUASI88/visualc/QUASI88.dsw
        modified:   RAQUASI88/visualc/QUASI88.ini
        modified:   RAQUASI88/visualc/QUASI88.sln
        modified:   RAQUASI88/visualc/QUASI88_sdl.dsp
        modified:   RAQUASI88/visualc/QUASI88_sdl.vcproj
        modified:   RAQUASI88/visualc/QUASI88_win32.dsp
        modified:   RAQUASI88/visualc/QUASI88_win32.vcproj

no changes added to commit (use "git add" and/or "git commit -a")

> git reset --hard
HEAD is now at ced4183 Merge commit '4e580eb2833ea26de6c148174cc12673db96f9f7' into quasi88

> git status
On branch quasi88
Your branch is up-to-date with 'origin/quasi88'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   RAQUASI88/src/snddrv-old/src/unix/sysdep/sysdep_sound_stream.c
        modified:   RAQUASI88/src/snddrv/license.txt
        modified:   RAQUASI88/src/snddrv/mame.txt
        modified:   RAQUASI88/visualc/KEYCONF.ini
        modified:   RAQUASI88/visualc/QUASI88.dsw
        modified:   RAQUASI88/visualc/QUASI88.ini
        modified:   RAQUASI88/visualc/QUASI88.sln
        modified:   RAQUASI88/visualc/QUASI88_sdl.dsp
        modified:   RAQUASI88/visualc/QUASI88_sdl.vcproj
        modified:   RAQUASI88/visualc/QUASI88_win32.dsp
        modified:   RAQUASI88/visualc/QUASI88_win32.vcproj

no changes added to commit (use "git add" and/or "git commit -a")
```

---------
[ ] submodule registrations need to be in the root `.gitmodule` file and use http URLs:
```
> git submodule init
fatal: No url found for submodule path 'RAQUASI88/dependencies/RAIntegration' in .gitmodules
```
I merged `RAQUASI88/.gitmodules` into `.gitmodules`, adding `RAQUASI88/` to both paths.
```
> git submodule init
Submodule 'RAQUASI88/dependencies/RAIntegration' (git@github.com:RetroAchievements/RAIntegration.git) registered for path 'RAQUASI88/dependencies/RAIntegration'
Submodule 'RAQUASI88/dependencies/SDL' (git@github.com:spurious/SDL-mirror.git) registered for path 'RAQUASI88/dependencies/SDL'
Submodule 'RA_Integration' (https://github.com/RetroAchievements/RAIntegration) registered for path 'RA_Integration'

> git submodule update --recursive
Cloning into 'E:/Source/RAEmus2/RAQUASI88/dependencies/RAIntegration'...
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:RetroAchievements/RAIntegration.git' into submodule path 'E:/Source/RAEmus2/RAQUASI88/dependencies/RAIntegration' failed
```
changed
```    url = git@github.com:RetroAchievements/RAIntegration.git```
to
```    url = https://github.com/RetroAchievements/RAIntegration```
and
```    url = git@github.com:spurious/SDL-mirror.git```
to
```    url = https://github.com/spurious/SDL-mirror```
```
> git submodule update --recursive
Cloning into 'E:/Source/RAEmus2/RAQUASI88/dependencies/RAIntegration'...
Cloning into 'E:/Source/RAEmus2/RAQUASI88/dependencies/SDL'...
Cloning into 'E:/Source/RAEmus2/RA_Integration'...
Submodule path 'RAQUASI88/dependencies/RAIntegration': checked out 'd843a8180121f0cc0922f1841da1cf5409655ba2'
Submodule path 'RAQUASI88/dependencies/SDL': checked out 'bd1a2ca5ca3d0a1e981e1e0318b796e393c2d0ae'
Submodule path 'RA_Integration': checked out '35ec2483ea5626e5c991f2d6d791d9cb054e70b3'
```

---------
[ ] project should use the `RA_Integration` submodule already available at the root, instead of having its own copy

---------
[ ] one of the projects in the solution fails to build. either fix it (preferred) or remove it
```
1>SDLmain.vcxproj -> E:\Source\RAEmus2\RAQUASI88\visualc\lib\Release_Win32\SDLmain.lib

3>SDL.vcxproj -> E:\Source\RAEmus2\RAQUASI88\visualc\lib\Release_Win32\SDL.dll
3>Done building project "SDL.vcxproj".

2>QUASI88_win32.vcxproj -> E:\Source\RAEmus2\RAQUASI88\visualc\./win32/Debug\QUASI88_win32.exe  <!-- output name should be RAQUASI88.exe
2>Done building project "QUASI88_win32.vcxproj".

4>RA_Interface.obj : error LNK2019: unresolved external symbol __imp___invalid_parameter referenced in function "void * __cdecl std::_Allocate_manually_vector_aligned<struct std::_Default_allocate_traits>(unsigned int)" (??$_Allocate_manually_vector_aligned@U_Default_allocate_traits@std@@@std@@YAPAXI@Z)
4>RA_Interface.obj : error LNK2019: unresolved external symbol __imp___CrtDbgReport referenced in function "void * __cdecl std::_Allocate_manually_vector_aligned<struct std::_Default_allocate_traits>(unsigned int)" (??$_Allocate_manually_vector_aligned@U_Default_allocate_traits@std@@@std@@YAPAXI@Z)
4>sdl/Debug/QUASI88.exe : fatal error LNK1120: 2 unresolved externals
4>Done building project "QUASI88_sdl.vcxproj" -- FAILED.
========== Build: 3 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

---------
[ ] The project output file should be `RAQUASI88.exe` so it's ready for immediate inclusion in the zip file. 

---------
[ ] Starting the debugger must start the application. Currently, the compiler generates a "QUASI88win32.exe", but the debugger tries to run "QUASI88_win32.exe".  This will probably be fixed by the previous task.

---------
After merging, we can ensure the emulator behaves like the other emulators. I've put together a checklist for expectations to meet before we can release. It's been reviewed by the admin team and GameDragon. We'll use this project as a trial run and polish it up, then commit it to the repository for any other future emulators.

[RAEmuChecklist.txt](https://github.com/RetroAchievements/RAEmus/files/2715297/RAEmuChecklist.txt)

**Comment by rzumer** [comment]
>[ ] A fresh checkout should not generate modified files. And why can't I make them go away?

Configuration-specific, due to EOL conversions. I recommend turning it off.

>[ ] submodule registrations need to be in the root .gitmodule file and use http URLs

Submodules were removed.

>[ ] project should use the RA_Integration submodule already available at the root, instead of having its own copy

Done.

>[ ] one of the projects in the solution fails to build. either fix it (preferred) or remove it

Cannot reproduce, but it is not compatible anyway, so use the new `RAQUASI88` solution that does not include it.

>[ ] The project output file should be RAQUASI88.exe so it's ready for immediate inclusion in the zip file.

Done.

>[ ] Starting the debugger must start the application. Currently, the compiler generates a "QUASI88win32.exe", but the debugger tries to run "QUASI88_win32.exe". This will probably be fixed by the previous task.

Done.

**Comment by rzumer** [comment]
It is mostly for compatibility, Visual Studio always uses CRLF so it can cause issues and force excessive reloads when git is also trying to normalize line endings. And since Visual Studio/MSBuild are the only applications that will use those files there is no advantage to normalizing their line endings.

The reason why it worked for you with a reset is because I had actually pushed changes to the .gitattributes. Try doing the same operation now, hopefully it will be compatible across both of our configurations. If not, then I can simply delete these old project files, they are not used for RA anyway.

After checking that `KEYCONF.ini` is read correctly with LF line endings, I changed it as well.

>Also, the debugger is still trying to run QUASI88_win32.exe.

Seems like changes made to the debugger are saved to a user configuration file by default. It should work now.

**Comment by Jamiras** [comment]
Just two remaining:
```
        modified:   RAQUASI88/visualc/QUASI88.dsw
        modified:   RAQUASI88/visualc/QUASI88.ini
```
Looks like you lost your last set of changes. The `RAQUASI\.gitmodules` is back, and the project is referencing `RAQUASI\dependencies\RAIntegration`.

I do see the debugging command referencing RAQUASI88.exe.

**Comment by rzumer** [comment]
Right, can't force-push anymore due to having additional changes on top of the subtree.

**Comment by Jamiras** [comment]
Project is still referencing the `dependencies\RAIntegration`.

image

Working Directory should be set to `$(TargetDir)`

**Pull request merged**
