### PR TITLE
Added VICE emulator

### PR DESCRIPTION
**Pull request by salvadorc17**
Added Vice c64 emulator with basic RA Integration code, still need to be polished.

### CODE REVIEW

**Comment by meleu** [comment]
Isn't https://github.com/libretro/vice-libretro good enough for cheevos? If yes, maybe it's easier to go through the RALibretro way.

**Comment by leiradel** [comment]
Adding new emulators in RALibretro has the additional benefit of making sure the cheevos will also work in RetroArch, even if with minor tweaks in the cheevos code there.

I'm seeing a lot of new emulators that also don't use RALibretro and I'm wondering if maybe the complexity of adding a new core to it is too high?

**Comment by rzumer** [comment]
@leiradel

> Adding new emulators in RALibretro has the additional benefit of making sure the cheevos will also work in RetroArch, even if with minor tweaks in the cheevos code there.

[As we've seen recently](https://github.com/libretro/RetroArch/issues/8582) it's not that simple, the implementation is different between RALR and RetroArch such that memory descriptors need special configuration to work correctly (on RA) when memory is mapped non-contiguously.

> I'm seeing a lot of new emulators that also don't use RALibretro and I'm wondering if maybe the complexity of adding a new core to it is too high?

All of my work was for systems that don't have libretro cores. Only PC-88 has one now, but it is missing features. I'm not sure there's a reason to use the standalone version here.

**Comment by leiradel** [comment]
> the implementation is different between RALR and RetroArch 

The implementations are different for emulators that already existed in the Retro Achievements ecosystem, because the official emulators map memory without any regard to their actual addresses.

For new emulators, it should be just a matter of asking the core maintainer to add/fix the memory maps for the system, and use them as-is in RALibretro. If the core maintainer is not available to do that then yes, adding the correct maps is not really trivial.

Also, that fix in the GBC memory map is wrong. The banked memory should've been mapped to its actual address, using the correct values for `start`, `select`, `disconnected`, and `len`, to map al the banks to that address, not to a fake address at 0x10000.

**Comment by salvadorc17** [comment]
Not really that core is wip and has lo of compatibility issues, but if you can do it yourself will be good.

**Comment by kdecks** [comment]
Would like to give my opinion here: While our policy is to focus on RALib and Retroarch support, anything that expands the library of games our developer can work on and our players can play is a good thing for the community. C64 is highly anticipated by many and I'm grateful for @salvadorc17 making the effort to expand our library!

In the past there have been emulators that @salvadorc17 brought in, and then later we transition to RALib (This happened with both NeoGeo Pocket and Atari Lynx). Perhaps this process could happen again?

The other side of it is, with each new stand-alone increases overall integration maintenance. It seems to me ultimately that this is @Jamiras's call.

**Comment by leiradel** [comment]
@kdecks I'm not saying that we shouldn't have standalone emulators, and I too welcome those developments. I'm just saying that when a libretro core is available, doing it via RALibretro helps to support achievements for that system in RetroArch with little effort, if any.

**Comment by Jamiras** [comment]
There's several problems we'd have to address to use the vice_x64 core:
1) The core "supports no content", which RALibRetro thinks it can't handle. So it refuses to even try loading the game. Ignoring that flag and passing the disk as the content seems to get the game to run, but I wasn't able to get past the title screen on any of the titles I tried - I'm not sure if the joystick button isn't properly mapped, or if it's waiting for me to do something else.
2) RALibRetro only has joystick support. It seems like the core itself has a joystick->keyboard psuedo-interface, but it's a very poor user experience given that we're running this on a machine that has an actual keyboard.
image
3) The core doesn't expose a memory map (0 descriptors), so we can't see the memory.
4) We need to be able to switch disk(s). This would behave the same as the PSX disc menu, but requires hooking it up to the C64 core.
5) The core doesn't support save states.
6) I don't know how the core supports games that write directly to the disk. For Apple II and PC8800, we store an "original" for hashing and pass a writable copy to the emulator. We'd probably need to do something similar here.

**Comment by Jamiras** [comment]
I had to make several changes to this tree to even get it to compile.
1) The code is looking for an RAIntegration folder at the top level. The submodule is `RA_Integration` (with an underscore).
2) Several changes had to be made to the .h file to allow it to be #include'd in a strictly-c compilation unit.
3) The winhttp library had to be added to the x64 project (there's several other projects that generate executables that it needs to be added to as well, but they aren't required to build the emulator itself)
4) archdep.c:473 - changed "free" to "lib_free" (this is likely a bug in the original source)

Then once I got it to compile, I spent way longer than I'd like to admit diagnosing the fact that I didn't have BIOS files. And once I got past that, I couldn't figure out how to get the keyboard to work. I did see it trying to resolve hashes when inserting disks, but that's the extent of the testing I was able to perform.

**Comment by rzumer** [comment]
You can use IPS for saving too. I couldn't find any non-GPL library to do this so [wrote one](https://github.com/rzumer/libreips/). It does not have great compression and cannot handle patches that change the file size, but that's not a problem for this use case.

**Comment by kdecks** [comment]
> RALibRetro only has joystick support. It seems like the core itself has a joystick->keyboard psuedo-interface, but it's a very poor user experience given that we're running this on a machine that has an actual keyboard.

Wouldn't this be a good enough reason to use vice? There are a number games that use the keyboard.

**Comment by salvadorc17** [comment]
There is any decition made here, i would like to know if will be added as core

**Comment by Jamiras** [comment]
I left a lot of feedback. As far as I can tell, you haven't addressed any of it.

**Comment by Jamiras** [comment]
Attempting to compile this still results in over 200 errors. Approximately half of them are because of bullet point 2 above, and the other half are because of bullet point 3.

> 2. Several changes had to be made to the .h file to allow it to be #include'd in a strictly-c compilation unit.
> 3. The winhttp library had to be added to the x64 project (there's several other projects that generate executables that it needs to be added to as well, but they aren't required to build the emulator itself)

Additionally, in regards to bullet point 1, the `arch.vcxproj` is still referencing the incorrect RAIntegration path: (https://github.com/RetroAchievements/RAEmus/blob/fdfe940d7672e66a42b35860e9495a7f8962948f/RAVICE/src/arch/win32/vs12/arch.vcxproj#L563, https://github.com/RetroAchievements/RAEmus/blob/fdfe940d7672e66a42b35860e9495a7f8962948f/RAVICE/src/arch/win32/vs12/arch.vcxproj#L781)

It is very difficult to do any sort of review for this PR as the diff has over 3 million lines of change. I would very much appreciate it if you followed the suggestions proposed in https://github.com/RetroAchievements/RAInterface/wiki/Creating-a-new-emulator and created a repository in your github containing the original emulator source, and provided a link to the branch/PR containing _only_ the changes necessary to convert it to an RA emulator.

**Comment by salvadorc17** [comment]
Ok no problem, will try that later.

**Comment by salvadorc17** [comment]
Can you explain me the deal with headers, you want this to be added.

#ifdef __cplusplus
extern "C" {

**Pull request closed without merging**
